# Generated by Django 4.1.5 on 2023-05-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0002_alter_commentaire_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='titre',
            field=models.CharField(default='Génial !', max_length=60),
            preserve_default=False,
        ),
    ]
